# Numpy Declaration

In [1]:
import numpy as np

# Numpy Initialization And Basic Functions

In [17]:
# Initializing the Array array1
array1 = np.array([12,14,16])

# Print array
print(array1)

# Print Array Dimensions i.e (1,2,3)
print(array1.ndim)

# Print Array Shape i.e (Row,Column)
print(array1.shape)

# Print Array DataType
print(array1.dtype)

[12 14 16]
1
(3,)
int64


In [18]:
# initializing the Array array2
array2 = np.array([[10,5,7],[12,9,8]])

# Print array
print(array2)

# Print Array Dimensions i.e (1,2,3)
print(array2.ndim)

# Print Array Shape i.e (Row,Column)
print(array2.shape)

# Print Array DataType
print(array2.dtype)


[[10  5  7]
 [12  9  8]]
2
(2, 3)
int64
